### ISSUE TITLE
add support for local fonts. especially fontawesome

### ISSUE THREAD

**Issue by mmilano** [mdziedzic/build-boilerplate-static-es6-sass#2]

**Comment by mdziedzic** [comment]
Until the added support arrives... https://www.bootstrapcdn.com/fontawesome/ Well, at least as far as fontawesome goes.

**Comment by mdziedzic** [comment]
Local font support to be added in v1.1.0. Not Font Awesome specifically, but as the CDN is a viable option considering the scope of this humble project, I am going to cross my fingers and hope that local Font Awesome support follows from local font support.
